env:
  browser: true
  node: true
extends: airbnb-base
installedESLint: true
rules:
  indent: ["error", 4]
  linebreak-style: ["error", "unix"]
  quotes: ["error","single"]
  semi: ["error", "always"]
  space-before-function-paren: ["error", "never"]
  comma-dangle: ["error", "never"]
  no-multiple-empty-lines: ["error", {
    max: 3,
    maxEOF: 1,
    maxBOF: 0
  }]
  no-confusing-arrow: 0
  arrow-parens: 0
  no-nested-ternary: 0
  no-param-reassign: 0
  no-unused-labels: ["error"]
  dot-notation: 0
  no-unused-vars: ["error", {
    vars: "all",
    args: "all"
  }]
plugins:
  - import
